"""Turn a theme JSON (themes/<name>.json or a custom file) into theme.css for one deck.

    python make_theme.py <theme.json | preset-name> <deck>/assets

Writes <assets>/theme.css and <assets>/theme.json (the copy diagrams.py reads), copies
logo files into <assets>/logos/ and the bundled font into <assets>/fonts/.
Colours, fonts and logos live ONLY here; studio.css (layout) never names a colour.

Theme JSON keys (all colours are hex):
  colors: brand brand2 accent hl hl_dk hl_lt tint tint_border hl_tint hl_border ink muted soft
          line paper surface grey row_alt on_brand on_brand_2 on_brand_rule on_accent on_hl
          backdrop good warn bad
  fonts:  sans display mono, bundled ("sarabun" or null), google (stylesheet URL or null)
  logos:  main main_dark partner partner_dark  (file paths or null; *_dark = for dark slides)
"""
import json
import shutil
import sys
from pathlib import Path

SKILL = Path(__file__).resolve().parent.parent
REQUIRED = ("brand brand2 accent hl hl_dk hl_lt tint tint_border hl_tint hl_border ink muted soft line "
            "paper surface grey row_alt on_brand on_brand_2 on_brand_rule on_accent on_hl backdrop good warn bad").split()


def _lum(h):
    h = h.lstrip("#")
    ch = [int(h[i:i + 2], 16) / 255 for i in (0, 2, 4)]
    ch = [c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4 for c in ch]
    return 0.2126 * ch[0] + 0.7152 * ch[1] + 0.0722 * ch[2]


def contrast(a, b):
    la, lb = sorted((_lum(a), _lum(b)), reverse=True)
    return (la + 0.05) / (lb + 0.05)


# (text, background, minimum): body text 4.5:1; hl carries only big bold numbers and labels, 3:1
CHECKS = [("on_brand", "brand", 4.5), ("on_accent", "accent", 4.5), ("ink", "paper", 4.5),
          ("muted", "paper", 4.5), ("brand", "hl_tint", 4.5), ("on_brand_2", "brand", 4.5),
          ("on_hl", "hl", 3.0), ("hl_lt", "brand", 3.0)]


def check_contrast(c):
    warn = []
    for fg, bg, need in CHECKS:
        r = contrast(c[fg], c[bg])
        if r < need:
            warn.append(f"  contrast {fg} on {bg} = {r:.2f}:1 (need {need}:1)")
    return warn


def load(spec):
    p = Path(spec)
    if not p.suffix:
        p = SKILL / "themes" / f"{spec}.json"
    t = json.loads(p.read_text(encoding="utf-8"))
    missing = [k for k in REQUIRED if k not in t["colors"]]
    if missing:
        raise SystemExit(f"{p.name}: missing colours {missing}")
    return t, p


def main(spec, assets):
    t, src = load(spec)
    assets = Path(assets)
    assets.mkdir(parents=True, exist_ok=True)
    c, f, logos = t["colors"], t["fonts"], t.get("logos") or {}

    css = [f"/* theme: {t.get('label', t['name'])} (generated by slide-studio make_theme.py, edit the JSON not this file) */"]
    if f.get("google"):
        css.append(f'@import url("{f["google"]}");')
    if f.get("bundled") == "sarabun":
        (assets / "fonts").mkdir(exist_ok=True)
        for w, n in ((300, "Light"), (400, "Regular"), (600, "SemiBold"), (700, "Bold")):
            shutil.copy(SKILL / "assets" / "fonts" / f"Sarabun-{n}.ttf", assets / "fonts")
            css.append(f'@font-face{{font-family:Sarabun;src:url("fonts/Sarabun-{n}.ttf") format("truetype");font-weight:{w}}}')
        shutil.copy(SKILL / "assets" / "fonts" / "OFL.txt", assets / "fonts")

    # logos: copied next to the theme so the deck folder is self-contained
    url = {}
    for key in ("main", "main_dark", "partner", "partner_dark"):
        path = logos.get(key)
        if path:
            lp = Path(path)
            if not lp.is_absolute():
                lp = (src.parent / lp).resolve()
            (assets / "logos").mkdir(exist_ok=True)
            shutil.copy(lp, assets / "logos" / lp.name)
            url[key] = f'url("logos/{lp.name}")'
    url.setdefault("main_dark", url.get("main", "none"))
    url.setdefault("partner_dark", url.get("partner", "none"))

    v = {k.replace("_", "-"): val for k, val in c.items()}
    v["brand-2"] = v.pop("brand2")
    lines = [f"  --{k}:{val};" for k, val in v.items()]
    lines += [
        f"  --font-sans:{f['sans']};", f"  --font-display:{f.get('display') or f['sans']};", f"  --font-mono:{f['mono']};",
        f"  --logo:{url.get('main', 'none')};", f"  --logo-dark:{url['main_dark']};",
        f"  --logo2:{url.get('partner', 'none')};", f"  --logo2-dark:{url['partner_dark']};",
        f"  --logo-pad:{'196px' if 'main' in url else '0px'};", f"  --logo2-w:{'58px' if 'partner' in url else '0px'};",
        f"  --hlogo-pad:{'25mm' if 'main' in url else '0mm'};", f"  --hlogo2-w:{'8.5mm' if 'partner' in url else '0mm'};",
        # html-ppt runtime tokens mapped onto the theme
        "  --bg:var(--paper); --bg-soft:var(--grey); --surface-2:var(--tint); --border:var(--line);",
        "  --text-1:var(--ink); --text-2:var(--muted); --text-3:var(--soft);",
        "  --accent-2:var(--accent); --accent-3:var(--hl); --accent-ink:var(--on-accent);",
        "  --radius:12px; --radius-sm:8px; --radius-lg:18px; --letter-tight:0; --letter-normal:0;",
    ]
    css.append(":root{\n" + "\n".join(lines) + "\n}")
    (assets / "theme.css").write_text("\n".join(css) + "\n", encoding="utf-8")
    (assets / "theme.json").write_text(json.dumps(t, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"theme {t['name']} -> {assets / 'theme.css'}")
    for w in check_contrast(c):
        print("WARNING" + w)


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    main(*sys.argv[1:])
